version: "3.8"

services:
    
    api:
      build:
          context: .
          dockerfile: Dockerfile
      image: realtemirov/encryption-bsc:test
      ports:
        - "8088:8088"
      env_file:
        - .env
      environment:
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_PORT=${POSTGRES_PORT}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      restart: always